### ISSUE TITLE
Nested object but different typenames

### ISSUE THREAD

**Issue by ecerroni** [lionize/apollo-link-response-resolver#1]
Kudos to this library. I always find myself reformatting responses from the server and your package allows me managing everything from a central point!

However, where there are query responses with a typename nested in another one, but different, it doesn't trigger the resolver. As an example:
```
{
  "data": {
    "currentUser": {
      "firstname": "Enrico",
      "lastname": "Cerroni",
      "email": "ric0@test.it",
      "company": {
        "name": "myCompany",
        "__typename": "Company"
      },
      "__typename": "User"
    }
  }
}
```
I thought I'd be able to handle it with the following resolvers:
```
const resolvers  = {
  User: {
    firstname: name => name.toUpperCase(),
    lastname: name => name.toUpperCase(),
  },
  Company: {
     name: name => name.toUpperCase(),
  },
};
```

It did not work. Instead, I made it work this way:
```
const resolvers  = {
  User: {
    firstname: name => name.toUpperCase(),
    lastname: name => name.toUpperCase(),
    company: company => ({ ...company, name: company.name.toUpperCase()}),
  },
};
```

Is that intended or I am doing something wrong?

**Comment by lionize** [comment]
Only five months late, but this now works as you expected in `0.1.0`!
